import { StoreProvider } from '@/redux/store-provider'
import { LanguageProvider } from '@/utils/translating/language-context'
import ClientLayout from './client-layout';
import "../app/css/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <StoreProvider>
        <LanguageProvider>
          <body
            className="antialiased"
          >
            <ClientLayout>{children}</ClientLayout>
          </body>
        </LanguageProvider>
      </StoreProvider>
    </html>
  );
}
